### ISSUE TITLE
How to use it missed

### ISSUE THREAD

**Issue by stevealexandre** [sazap10/ovh-dyndns-updater#1]
How to use it?
I don't understand how to set env var to use in the container.

**Comment by sazap10** [comment]
You can run it either through docker-compose or through docker run using `docker run -e DOMAIN=[domain name] -e USERNAME=[username] -e PASSWORD=[password] sazap10/ovh-dyndns-updater:latest -d`

**Comment by stevealexandre** [comment]
Seems ok for run now but when I run it i'm blocked in ghost tty which force me to restart my ssh console.
There are a way to know if the updated as working successfully? Because my IP has not changed for moment but one day maybe.

**Comment by sazap10** [comment]
The -d switch shouldnt put you into a ghost tty. Its been working for me for a year or so

**Comment by stevealexandre** [comment]
This is what I get with -d
container_linux.go:247: starting container process caused "exec: \"-d\": executable file not found in $PATH"
docker: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "exec: \"-d\": executable file not found in $PATH".
ERRO[0000] error getting events from daemon: net/http: request canceled

**Comment by stevealexandre** [comment]
Ok solved by putting -d before -e
