### ISSUE TITLE
Update multiple subdomains

### ISSUE THREAD

**Issue by Mr-Oca** [sazap10/ovh-dyndns-updater#2]
Hi !
Everything is in the title : I'd like to update mulitple subdomains (aa.domain.com, bb.domain.com, etc). Is it possible ?
If yes, how to do it ?
Thanks.

**Comment by sazap10** [comment]
Probably worth using https://github.com/sazap10/ovh-ip-updater-go which has support for multiple domains

**Comment by Mr-Oca** [comment]
Perfect, thank you !

**Comment by sazap10** [comment]
Let me know if you have any issues running it

**Comment by Mr-Oca** [comment]
Works perfectly fine. Seems to take a little bit of time to update the ip though.

**Comment by sazap10** [comment]
Great! Hmm usually it's instant, it could be DNS caching possibly.

**Comment by Mr-Oca** [comment]
Well, when i start the docker (or restart the NAS), it IS instant. But if I reboot my box to change my ip, it takes some times (didn't mesure it).

**Comment by sazap10** [comment]
Ah ok, it might be the time it takes for docker and the container to be up and running after a reboot

**Comment by Mr-Oca** [comment]
No, that's the opposite : after a reboot, it is instant.
But whith docker and container running, if I change my IP, then it takes some times. Maybe the container only read IP every XX minutes ?

**Comment by sazap10** [comment]
Ah yeh, it rechecks every hour. I do plan to make that configurable at some point
